Repository adopted-ember-addons/ember-collapsible-panel, pull requests merged in 2021-11, with the labels that each got.

#92 Drop Node < 12, 13, and 15.
  config/ember-try.js
  package.json
Labels: breaking

#93 Update ember-cli-babel@7 & ember-cli-htmlbars@6
  package.json
  yarn.lock
Labels: breaking

#95 Fixup usage of ember-code-snippet
  tests/dummy/app/pods/demo/accordion-usage/template.hbs
  tests/dummy/app/pods/demo/basic-usage/template.hbs
  tests/dummy/app/pods/demo/disabled-panel/template.hbs
  tests/dummy/app/pods/demo/nested-panels/template.hbs
  tests/dummy/app/pods/demo/one-way-binding/template.hbs
  tests/dummy/app/pods/demo/programmatic-control/template.hbs
  tests/dummy/app/pods/demo/start-out-open/template.hbs
  tests/dummy/app/pods/demo/template.hbs
Labels: internal

#96 Re-roll yarn.lock
  yarn.lock
Labels: internal

#97 Update to modern testing setup
  package.json
  tests/index.html
  tests/integration/cp-panel-test.js
  tests/integration/cp-panel-toggle-test.js
  tests/integration/cp-panels-test.js
  tests/unit/services/panel-actions-test.js
  yarn.lock
Labels: internal

#99 Update ember-source to 3.28
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: internal

#87 Fix usage under Embroider
  .github/workflows/ci.yml
  addon/components/cp-panel-body/component.js
  addon/components/cp-panel-body/template.hbs
  addon/components/cp-panel/component.js
  addon/services/dependency-checker.js
  app/services/dependency-checker.js
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  index.js
  package.json
  yarn.lock
Labels: bug
